# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 536)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FunctionInput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.FunctionInput.setGeometry(QtCore.QRect(20, 120, 300, 30))
        self.FunctionInput.setObjectName("FunctionInput")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 301, 16))
        self.label.setObjectName("label")
        self.FunctionIsCorrect = QtWidgets.QLabel(parent=self.centralwidget)
        self.FunctionIsCorrect.setGeometry(QtCore.QRect(20, 160, 301, 16))
        self.FunctionIsCorrect.setObjectName("FunctionIsCorrect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Графический калькулятор"))
        self.label.setText(_translate("MainWindow", "Введите математическую функцию"))
        self.FunctionIsCorrect.setText(_translate("MainWindow", "Статус: "))
