# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    Класс главного окна приложения, описывающий используемые в нём виджеты
    """
    def setupUi(self, MainWindow):
        """
        Функция, инициализирующая главное окно и его виджеты
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 536)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FunctionInput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.FunctionInput.setGeometry(QtCore.QRect(50, 129, 191, 21))
        self.FunctionInput.setObjectName("FunctionInput")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 231, 16))
        self.label.setObjectName("label")
        self.FunctionIsCorrect = QtWidgets.QLabel(parent=self.centralwidget)
        self.FunctionIsCorrect.setGeometry(QtCore.QRect(20, 190, 301, 16))
        self.FunctionIsCorrect.setObjectName("FunctionIsCorrect")
        self.AddFuncButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddFuncButton.setGeometry(QtCore.QRect(130, 150, 113, 32))
        self.AddFuncButton.setObjectName("AddFuncButton")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 21, 16))
        self.label_2.setObjectName("label_2")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(260, 20, 400, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 60, 16))
        self.label_3.setObjectName("label_3")
        self.ColorSeletButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ColorSeletButton.setGeometry(QtCore.QRect(60, 160, 61, 21))
        self.ColorSeletButton.setStyleSheet("background-color: red")
        self.ColorSeletButton.setText("")
        self.ColorSeletButton.setObjectName("ColorSeletButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Графический калькулятор"))
        self.label.setText(_translate("MainWindow", "Введите математическую функцию"))
        self.FunctionIsCorrect.setText(_translate("MainWindow", "Статус: "))
        self.AddFuncButton.setText(_translate("MainWindow", "Добавить"))
        self.label_2.setText(_translate("MainWindow", "y = "))
        self.label_3.setText(_translate("MainWindow", "Цвет:"))
